export type ModalType = 
| 'CREATE_PROJETO' 
| 'CREATE_PROPOSTA' 
| 'CREATE_CONTRATO' 
| 'CREATE_CLIENTE' 
| 'CREATE_EMAIL'
| 'CONFIRM'
| 'SETTINGS_PROJETO'
| 'SETTINGS_PROPOSTA'
| 'SETTINGS_CONTRATO';