name: Angular GitHub CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: /dist/flowly

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm run test:prod

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: deploy
      - name: Deploy
        run: aws s3 cp sync ./dist/flowly s3://flowly-dev --aclpublic-read
